Add load balancer defaults via env
hetznercloud/hcloud-cloud-controller-manager pull request #114
Opened 2020-11-10 13:23 UTC by 0SkillAllLuck

Add env for: 
- HCLOUD_LOAD_BALANCERS_DEFAULT_LOCATION
- HCLOUD_LOAD_BALANCERS_DEFAULT_NETWORK_ZONE
- HCLOUD_LOAD_BALANCERS_DEFAULT_USE_PRIVATE_IP

HCLOUD_LOAD_BALANCERS_DEFAULT_LOCATION and HCLOUD_LOAD_BALANCERS_DEFAULT_NETWORK_ZONE help with the error of "neither load-balancer.hetzner.cloud/location or load-balancer.hetzner.cloud/network-zone are set".
This removes the need to set these annotations over and over again if the cluster is only in a single location.

2020-11-12 06:04 UTC, LKaemmerling requested changes
Hey @0SkillAllLuck, thank you for your contribution! I have a few smaller things. Could you also please add test cases to `internal/hcops/load_balancer_test.go`?

2020-11-12 06:04 UTC, LKaemmerling commented on internal/hcops/load_balancer.go
> +			klog.Info("Not set")
Could you please remove the debug line?

2020-11-12 06:04 UTC, LKaemmerling commented on internal/hcops/load_balancer.go
> +					klog.Info("to bool failed")
This too

2020-11-12 06:04 UTC, LKaemmerling commented on internal/hcops/load_balancer.go
> +				klog.Info("ok")
Too

2020-11-12 06:04 UTC, LKaemmerling commented on internal/hcops/load_balancer.go
> +				klog.Info("no default")
Too :)

2020-11-19 07:17 UTC, LKaemmerling commented
@0SkillAllLuck could you please rebase against master? Then the tests should be executed.

2020-11-19 07:52 UTC, 0SkillAllLuck commented
Added HCLOUD_LOAD_BALANCERS_DEFAULT_DISABLE_PRIVATE_INGRESS to potentially help with #118. When only the public ingress is needed.

2020-11-19 08:03 UTC, 0SkillAllLuck commented
@LKaemmerling rebased against master.

2020-11-26 07:10 UTC, LKaemmerling commented
@0SkillAllLuck we were thinking about this a lot. 
It looks like there are a few changes in there that shouldn't be there :) Also, we think that the ENV names are really too long and not documented at all, so we would like to come up with our own solution within the next couple of weeks. Therefore, thank you for your work on this but unfortunately, we decided to reject this merge request.

2020-11-26 07:10 UTC, closed without merging