fix(helm-chart): resource namespace and name
hetznercloud/hcloud-cloud-controller-manager pull request #462
Opened 2023-06-28 20:17 UTC by simonostendorf

This should fix the issue that you can change the release namespace with helm, but the deployment will not take care of it. 

Also this allows the user to use the nameoverwrite that was already defined inside the chart helpers.

2023-06-29 08:25 UTC, apricote requested changes
Nice! Could you update the field in the [ClusterRoleBinding](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/185a5c0080bcd5403070f702e93cae2247cff120/chart/templates/clusterrolebinding.yaml#L11-L12) to match the new name(+space) of the ServiceAccount?

2023-06-29 08:51 UTC, apricote approved these changes

2023-06-29 09:39 UTC, simonostendorf commented
> Nice! Could you update the field in the [ClusterRoleBinding](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/185a5c0080bcd5403070f702e93cae2247cff120/chart/templates/clusterrolebinding.yaml#L11-L12) to match the new name(+space) of the ServiceAccount?

Sorry i forgot to change it there.

2023-07-05 07:54 UTC, apricote commented
Sorry for the delay. Our e2e tests are currently broken for PRs from forks and I wanted to run them locally. I found that in the e2e tests we do not set the Helm Chart namespace which caused the pods to run in `default`. The required secret was added to `kube-system` though. I [added the namespace](https://github.com/hetznercloud/hcloud-cloud-controller-manager/pull/462/commits/26319b9b87af40c4548578f54c890f46fb96dbb7) for our E2E tests and they succeeded locally.

2023-07-05 07:54 UTC, apricote approved these changes

2023-07-05 07:55 UTC, merged