Specify private ip for loadbalancer
hetznercloud/hcloud-cloud-controller-manager pull request #724
Opened 2024-08-19 13:07 UTC by lhp-nemlig

Allows users to specify the IPv4 of the load balancer in the private network via the annotation "load-balancer.hetzner.cloud/private-ipv4"

Removes network logic from main load balancer creation, since the API does not support specifying the IP address there, and moves network logic to exclusively happen in AttachToNetwork and DetachFromNetwork.

I also added an extra LoadBalancer refresh in the main reconciliation loop, since changing the IP address of an SVC object causes network detach and subsequent attach, which in turn needs to cause the targets to be re-added to loadbalancer if they were private network targets.

Unit tests pass and i have tested this in a few scenarios on a cluster of my own.

2024-09-02 13:08 UTC, apricote commented
Just to make sure we are on the same page:

Instead of assigning a random/next IP to the Load Balancer in the private Network, you want to explicitly set the IP that the Load Balancer should have (through an annotation).

Did I understand you correctly?

2024-09-02 13:11 UTC, lhp-nemlig commented
Yes that is correct, and this PR accomplishes that.

If explicitly setting an IP was not possible, reserving a set of IP's for VM's would be impossible as the load balancers could randomly make use of them.

2024-09-02 14:18 UTC, apricote requested changes
Two small nits. I had some trouble running the e2e tests today, will try again tomorrow.

2024-09-03 05:38 UTC, apricote commented
E2E tests are successful.

2024-09-03 07:24 UTC, lhp-nemlig commented on hcloud/load_balancers.go
> +	}
Added comment

2024-09-03 07:24 UTC, lhp-nemlig commented on internal/hcops/load_balancer.go
> +	NetworkIPv4   net.IP
Removed leftover field

2024-09-03 07:48 UTC, merged